
UPDATE menu_items SET price = 6.9 WHERE name = 'Caldo de Carne c/ Mandioca';
UPDATE menu_items SET price = 6.9 WHERE name = 'Caldo de Feijão';
UPDATE menu_items SET price = 6.9 WHERE name = 'Caldo de Frango';
UPDATE menu_items SET price = 6.9 WHERE name = 'Caldo Verde';
UPDATE menu_items SET price = 10.8 WHERE name = 'Executivo Clássico';
UPDATE menu_items SET price = 10.9 WHERE name = 'Executivo do Chefe';
UPDATE menu_items SET price = 10.8 WHERE name = 'Executivo Dom Bistrô';
UPDATE menu_items SET price = 11.2 WHERE name = 'Executivo Festa Brasileira';
UPDATE menu_items SET price = 10.8 WHERE name = 'Executivo Parmegiana';
UPDATE menu_items SET price = 11.2 WHERE name = 'Feijoada Completa';
UPDATE menu_items SET price = 10.8 WHERE name = 'Jantinha de Espetinhos';
UPDATE menu_items SET price = 15.8 WHERE name = 'Picanha';
UPDATE menu_items SET price = 3.9 WHERE name = 'Bolo de Cenoura';
UPDATE menu_items SET price = 3.9 WHERE name = 'Bolo de Chocolate';
UPDATE menu_items SET price = 2.5 WHERE name = 'Bolo de Leite Ninho';
UPDATE menu_items SET price = 3.5 WHERE name = 'Bolo de Milho';
UPDATE menu_items SET price = 4.5 WHERE name = 'Bolo de Ninho';
UPDATE menu_items SET price = 5.8 WHERE name = 'Bolo de Pote';
UPDATE menu_items SET price = 3.5 WHERE name = 'Bolo Formigueiro';
UPDATE menu_items SET price = 1.3 WHERE name = 'Brigadeiro';
UPDATE menu_items SET price = 4.5 WHERE name = 'Pudim';
UPDATE menu_items SET price = 9.5 WHERE name = 'Panelinha Bacon c/ Linguiça';
UPDATE menu_items SET price = 9.5 WHERE name = 'Panelinha de Bacon';
UPDATE menu_items SET price = 9.5 WHERE name = 'Panelinha de Carne';
UPDATE menu_items SET price = 9.5 WHERE name = 'Panelinha de Legumes';
UPDATE menu_items SET price = 9.2 WHERE name = 'X-Baguncinha';
UPDATE menu_items SET price = 14.3 WHERE name = 'X-Brasileiro';
UPDATE menu_items SET price = 10.2 WHERE name = 'X-Carioca';
UPDATE menu_items SET price = 15.5 WHERE name = 'X-Dom Cheddar';
UPDATE menu_items SET price = 12.2 WHERE name = 'X-Gauchesco';
UPDATE menu_items SET price = 10.8 WHERE name = 'X-Mineiro';
UPDATE menu_items SET price = 12.8 WHERE name = 'X-Nordestino';
UPDATE menu_items SET price = 6.0 WHERE name = 'Anéis de Cebola';
UPDATE menu_items SET price = 8.2 WHERE name = 'Asinha de Frango ao Molho Agridoce';
UPDATE menu_items SET price = 7.8 WHERE name = 'Batata Frita com Nutela e Leite Nido';
UPDATE menu_items SET price = 7.8 WHERE name = 'Batatas Fritas G';
UPDATE menu_items SET price = 5.5 WHERE name = 'Batatas Fritas M';
UPDATE menu_items SET price = 3.5 WHERE name = 'Batatas Fritas P';
UPDATE menu_items SET price = 7.8 WHERE name = 'Calabresa Acebolada';
UPDATE menu_items SET price = 7.8 WHERE name = 'Cuscuz com Ovo e Queijo Coalho';
UPDATE menu_items SET price = 3.9 WHERE name = 'Pastel de Carne';
UPDATE menu_items SET price = 3.9 WHERE name = 'Pastel de Frango';
UPDATE menu_items SET price = 1.9 WHERE name = 'Água com Gás';
UPDATE menu_items SET price = 2.2 WHERE name = 'Água das Pedras Limão';
UPDATE menu_items SET price = 1.8 WHERE name = 'Água Mineral';
UPDATE menu_items SET price = 2.2 WHERE name = 'Coca-Cola';
UPDATE menu_items SET price = 2.8 WHERE name = 'Coca-Cola Zero';
UPDATE menu_items SET price = 4.5 WHERE name = 'Creme de Morango';
UPDATE menu_items SET price = 2.2 WHERE name = 'Guaraná Antarctica';
UPDATE menu_items SET price = 2.5 WHERE name = 'Ice Tea';
UPDATE menu_items SET price = 2.5 WHERE name = 'Seven Up';
UPDATE menu_items SET price = 3.2 WHERE name = 'Suco Natural de Laranja';
UPDATE menu_items SET price = 3.2 WHERE name = 'Suco Natural de Maracujá';
UPDATE menu_items SET price = 3.9 WHERE name = 'Sumo Natural Abacaxi';
UPDATE menu_items SET price = 3.9 WHERE name = 'Sumo Natural Laranja';
UPDATE menu_items SET price = 2.2 WHERE name = 'Sumol';
UPDATE menu_items SET price = 2.2 WHERE name = 'Sumol Ananás';
UPDATE menu_items SET price = 2.9 WHERE name = 'Super Bock';
UPDATE menu_items SET price = 6.3 WHERE name = 'Espetinho de Carne';
UPDATE menu_items SET price = 5.0 WHERE name = 'Espetinho de Coalho c/ Melaço';
UPDATE menu_items SET price = 5.0 WHERE name = 'Espetinho de Frango';
UPDATE menu_items SET price = 5.8 WHERE name = 'Espetinho de Frango c/ Bacon';
UPDATE menu_items SET price = 5.3 WHERE name = 'Espetinho de Linguiça';
UPDATE menu_items SET price = 4.2 WHERE name = 'Espetinho de Queijo Coalho';
